# Generated by Django 5.0.2 on 2024-03-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
